GET http://localhost:8080/

###

POST http://localhost:8080/
Content-Type: application/json

{
  "user": "alo2",
  "message": "This is the second post test message",
  "date": "2023-09-20T16:15:00.000Z"
}